
FROM node:20.18-alpine3.20 AS base

# ------ Setup Postgres ------
RUN apk update && apk add postgresql

RUN mkdir -p /var/lib/postgresql/data \
    && chown -R postgres:postgres /var/lib/postgresql \
    && mkdir -p /var/run/postgresql \
    && chown -R postgres:postgres /var/run/postgresql

USER postgres
RUN initdb -D /var/lib/postgresql/data
RUN sed -i "s/^#listen_addresses =.*/listen_addresses = '*'/" /var/lib/postgresql/data/postgresql.conf
USER root
# ------ End Setup Postgres ------

# ------ Setup MinIO ------
RUN wget https://dl.min.io/server/minio/release/linux-amd64/minio
RUN mv minio /usr/local/bin/
RUN chmod +x /usr/local/bin/minio

# Install MinIO client
RUN wget https://dl.min.io/client/mc/release/linux-amd64/mc
RUN chmod +x mc
RUN mv mc /usr/local/bin/
# ------ End Setup MinIO ------

FROM base AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
RUN apk update

# Produce a pruned version of the monorepo
WORKDIR /app
RUN npm install -g turbo@2.0.1
COPY . .
RUN turbo prune @fern-platform/fdr --docker


# Add lockfile and package.json's
FROM base AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
RUN npm install -g pnpm@v9.4.0
WORKDIR /app

# Install deps
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml .
RUN pnpm install

ARG FERN_TOKEN
ENV FERN_TOKEN=$FERN_TOKEN

# Build
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
COPY shared shared
COPY fern fern
RUN pnpm turbo --filter=@fern-platform/fdr codegen
RUN pnpm turbo --filter=@fern-platform/fdr compile

FROM base AS runner
WORKDIR /app

RUN npm install -g prisma pnpm@v9.4.0

ENV DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
ENV LOCAL_MODE_OVERRIDE=true

# Uncomment this when we want to allow local overrides
# ARG ORG_NAME=plantstore
ENV ORG_NAME=plantstore
ENV MINIO_REGION=global

# Modify /etc/hosts
# 127.0.0.1 minio-fern.localhost% 

# Replace this when we the fern-cli with auth override is available via npm
RUN mkdir -p /usr/local/lib/fern
COPY fern-cli.tar.gz /usr/local/lib/fern/fern-cli.tar.gz
RUN tar -xzf /usr/local/lib/fern/fern-cli.tar.gz -C /usr/local/lib/fern

COPY --from=installer /app .

COPY packages /app/packages
COPY packages/fern-docs /app/packages/fern-docs

ENTRYPOINT ["/bin/sh", "/app/servers/fdr/scripts/run_aio.sh"]
